- name: Install Zookeeper
  ansible.builtin.include_tasks: install_zookeeper.yml
  when: inventory_hostname in groups['zookeeper_nodes']

- name: Install ClickHouse
  ansible.builtin.include_tasks: install_clickhouse.yml

- name: Configure ClickHouse cluster
  ansible.builtin.include_tasks: configure_cluster.yml
